POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName" : "ch19-state-store",
  "tel" : "111-222-333",
  "address" : "USA",
  "company" : "nhn"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderID" : "5bddd703-cae3-4d6f-a0b0-80f4e0e33f38"
}

### 0041f839-4ea4-42bf-94ca-6ebcbdaaf2ee

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountID" : "37ddb7c8-0d3b-443d-a6d5-c83d873f0521",
  "holderID" : "e5775054-4265-46ef-8116-297ac22f480d",
  "amount" : 400
}

###

POST http://localhost:8080/withdrawal
Content-Type: application/json

{
  "accountID" : "fffb8fa2-94dd-4e84-b7fd-072d09d01d33",
  "holderID" : "e5775054-4265-46ef-8116-297ac22f480d",
  "amount" : 10
}

###

POST http://localhost:8080/transfer
Content-Type: application/json

{
	"srcAccountID" : "test-sender",
	"dstAccountID" : "fd9f5bd5-740f-4535-a16a-a28b84d89926",
	"amount" : 150,
	"bankType" : "JEJU"
}
