POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName" : "melvin",
  "tel" : "02-1234-5678",
  "address" : "OO시 OO구 hehe"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderID" : "65cc77b7-6820-472d-ba72-dd942f801f21"
}

### 0041f839-4ea4-42bf-94ca-6ebcbdaaf2ee

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountID" : "fffb8fa2-94dd-4e84-b7fd-072d09d01d33",
  "holderID" : "65cc77b7-6820-472d-ba72-dd942f801f21",
  "amount" : 400
}

###

POST http://localhost:8080/withdrawal
Content-Type: application/json

{
  "accountID" : "fffb8fa2-94dd-4e84-b7fd-072d09d01d33",
  "holderID" : "65cc77b7-6820-472d-ba72-dd942f801f21",
  "amount" : 10
}

###