server:
  port: 8080

spring:
  application:
    name: eventsourcing-cqrs-command
  datasource:
    url: jdbc:postgresql://192.168.35.100:5432/command
    username: command
    password: command
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

#  sql:
#    init:
#      platform: postgres

axon:
  serializer:
    general: xstream
  axonserver:
    servers: 192.168.35.100:8124
  eventhandling:
    processors:
      name:
        mode: tracking

logging:
  level:
    com:
      cqrs:
        command: debug
    org:
      axonframework: debug